spring:
  config:
    import: optional:file:.env[.properties]

  servlet:
    multipart:
      enabled: true  # ???? ??? ?? ??
      max-file-size: 10MB
      max-request-size: 50MB
      location: /tmp  # ?? ?? (??? OS ???)

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    # show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
  devtools:
    restart:
      enabled: true     # spring boot ?????? ??? ???
    livereload:
      enabled: true # ???? ?? ?? ????

springdoc:
  swagger-ui:
    # 접속 경로를 http://localhost:8080/swagger 로 변경
    path: /swagger
  # API 그룹화나 정렬 설정
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secretKey: ${JWT_SECRET_KEY:secretKey}
  # accessTokenExpiration,
  access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:3600000}


logging:
  level:
    org.hibernate.sql: debug # (Show-sql: true)
    org.hibernate.orm.jdbc.bind: trace
#    org.springframework.web.servlet.mvc.method.annotation: TRACE
#    org.springframework.http.converter: TRACE